language: node_js
node_js:
    - 13
cache:
    directories:
        - dist/components
        - dist/doc-lib
        - dist/examples
stages:
    - prepare
    - build-components-lib
    - build-doc-lib
    - build-app-aot
    - test
    - publish
    - deploy
jobs:
    include:
        #        - stage: prepare
        #          name: Lint /components
        #          script: npm run lint components
        #        - stage: prepare
        #          name: Lint /doc-lib
        #          script: npm run lint doc-lib
        #        - stage: prepare
        #          name: Lint /examples
        #          script: npm run lint examples

        - stage: build-components-lib
          name: Build /components
          script: npm run build:components

        #        - stage: build-doc-lib
        #          name: Build /doc-lib
        #          script: npm run build:doc-lib

        #        - stage: build-app-aot
        #          name: Build /examples
        #          before_script:
        #              - cd ./projects/doc-lib
        #              - npm install
        #              - npm link
        #              - cd ../../
        #              - npm run build-components-doc
        #              - npm run build-examples-doc
        #          script:
        #              npm run build:examples-aot

        #        - stage: test
        #          name: Unit tests for /components
        #          script: npm run test:ci:components
        #        - stage: test
        #          name: Unit Tests for /doc-lib
        #          script: npm run test:ci:doc-lib

        - stage: publish
          name: Publishing components to npm registry
          script: echo "Deploying @ps37${TRAVIS_TAG} to npm..."
          before_deploy:
              - cd ./dist/components
          deploy:
              edge: true
              provider: npm
              email: prudhvi.af121@gmail.com
              api_key:
                  secure: vFxxLJUkMhPdb5wqs8BW9bxsySmSCSBxwTWRqyMksSbC1qqmBQFlltkQbEOeom48mh0Gl5MOJ0PUzTjt5Q8JmqMKZaNxk5A85H9G0lkY03IuC2to3dd4Gb9SavQ8zhg8o2Rz8hwTkiZ0N67S1SaWN0EkeSNqq/B0IRWtpm7LHteNr3yfGPvFjYMmHZhc5OieLEnZ/BPi/IAOchzHmNfM8JpmVXeWptx9G/YcFSCXfIpjkYRXsA0ar82NlJIXpvzYDNUWnAEwgTEGSsmCN0OV89plmdaB+zNL4iqNem5r4pNiQe4i5wj1XVEdms46Q1kWyo/hEASYiiRrqGS9K09r65tbKgdPuMH5rXNUbUmi/N08IdySX2J7STNUUoHebYkDSoEKSXMQNu5XHhidtZ9dfr9ukg9wpefpvyCVLC2MbldM9fLPGeqrUBrh1hG81LbG4LRiDebZG/LijvyQuz/ts3Dw0ihwq/nQTMk9V3LDCu0FHuiADWszKRu2hci/JgxG65w23peY08dfBQxVg6+SplBe60F+ImKsTiqmFDyNqyqBzXvek8kj8QqjXzjJ5fxxyBELaqPJJl1Ibqs4NJalZ2beUALPmB/DH2SrLNeWlYXkQ2ray4ogSsuUjFzSuSh7UeZCI8kEXSC2cbZdCdIND1Wsp+jkHPQxZxCR+4oB9KE=
              on:
                  repo: ps37/vmware-cloud-director-ui-components
                  tags: true
                  condition: $TRAVIS_TAG =~ /^components-v\d.\d.\d$/
        #        - stage: deploy
        #          name: Deploying to Github pages
        #          script: skip
        #          deploy:
        #              - provider: pages
        #                skip_cleanup: true
        #                github_token: $GH_TOKEN
        #                local_dir: dist/examples
