language: node_js
node_js:
    - 13
cache:
    directories:
        - dist/components
        - dist/doc-lib
        - dist/examples
stages:
    - prepare
    - build-components-lib
    - build-doc-lib
    - build-app-aot
    - test
    - name: publish
      if: branch = master OR branch = travis-test-4
    - deploy
jobs:
    include:
        #        - stage: prepare
        #          name: Lint /components
        #          script: npm run lint components
        #        - stage: prepare
        #          name: Lint /doc-lib
        #          script: npm run lint doc-lib
        #        - stage: prepare
        #          name: Lint /examples
        #          script: npm run lint examples

        - stage: build-components-lib
          name: Build /components
          script: npm run build:components

        #        - stage: build-doc-lib
        #          name: Build /doc-lib
        #          script: npm run build:doc-lib

        #        - stage: build-app-aot
        #          name: Build /examples
        #          before_script:
        #              - cd ./projects/doc-lib
        #              - npm install
        #              - npm link
        #              - cd ../../
        #              - npm run build-components-doc
        #              - npm run build-examples-doc
        #          script:
        #              npm run build:examples-aot

        #        - stage: test
        #          name: Unit tests for /components
        #          script: npm run test:ci:components
        #        - stage: test
        #          name: Unit Tests for /doc-lib
        #          script: npm run test:ci:doc-lib

        - stage: publish
          name: Publishing components to npm registry
          script: echo "Deploying to npm user psimhadri..."
          deploy:
              provider: npm
              email: prudhvi.af121@gmail.com
              api_key:
                  secure: WYQNGz1JOI/hcLoFdubl2QXsn4qFPihGHOp822K/8rjdLQ+T8UOYj+tk8OGBal6q5uG/+oZt/Scd8xYpH23L5NAeglcFBw78vnsRopGgG38IzYVqkVfE+2Qs9CveLhXXWiKhoFhwVqfDmLiJ4rbQLb99OY0ZXpcJYUVQjkI7vG7DHD+mxv4/OUKSzg9DWk+ujfdS8GCapJ2znls4+jp1FKhQzUODNZCS9MO9sYHFgd/gA28FF1UdRamc7QqS1JClHDqJ3MUyXpQZ0PWERgPZG31s3WB6VHMJgiifzsJsGu0egl7kXLEtVzvEGc5qhMPFl36S+YmjTyZA1FH2U6sSoubgAsF4l0+VpJ+98T1GVb38U36qgg7QHF6ANX8Rgv9AXSlg/OTBYOE6R2KO/Ydmxfe5vp6yfFiAqL5OEvgiBmpF9RTF7WxF/VgfD/1dI/HYVctxdskE8W7sTQmtPCmZf9SDBTLk1fvHfp7Iqyd8oguNRpNda5itvvwslosrVkdpBr3ScAZW0w7TBS94Qa/G/Q6j6iIOpEldQw1tWglOQ1ZCkoi6FPrjJxwk4WMSJ/4a1S7FBus7voaTsx3a/cmPgGojWUlJl2rtBaKmu79loxQIJRmDE080lj4IAQlV47XVM9vLR/b27+emjON8EuSfxXGNxki81zLeu4Xs1rVQMOQ=
              on:
                  repo: ps37/vmware-cloud-director-ui-components
                  branch: travis-test-4
              local_dir: dist/components
        #        - stage: deploy
        #          name: Deploying to Github pages
        #          script: skip
        #          deploy:
        #              - provider: pages
        #                skip_cleanup: true
        #                github_token: $GH_TOKEN
        #                local_dir: dist/examples
