language: node_js
node_js:
    - 13
cache:
    directories:
        - dist/components
        - dist/doc-lib
        #        - projects/examples/gen/components-compodoc-documentation
        #        - projects/examples/gen/examples-compodoc-documentation
        - dist/examples

stages:
    - prepare
    - build-components-lib
    - build-doc-lib
    - build-app-aot
    - test
    - name: publish
      if: branch = master
    - deploy

jobs:
    include:
        #        - stage: prepare
        #          name: Lint /components
        #          script: npm run lint components
        #        - stage: prepare
        #          name: Lint /doc-lib
        #          script: npm run lint doc-lib
        #        - stage: prepare
        #          name: Lint /examples
        #          script: npm run lint examples

        - stage: build-components-lib
          name: Build /components
          script: npm run build:components

        - stage: build-doc-lib
          name: Build /doc-lib
          script: npm run build:doc-lib

        - stage: build-app-aot
          name: Build /examples
          before_script:
              - cd ./projects/doc-lib
              - npm install
              - npm link
              - cd ../../
              - npm run build-components-doc
              - npm run build-examples-doc
          script: npm run build:examples-aot

        #        - stage: test
        #          name: Unit tests for /components
        #          script: npm run test:ci:components

        #        - stage: test
        #          name: Unit Tests for /doc-lib
        #          script: npm run test:ci:doc-lib

        - stage: deploy
          name: Deploying to Github pages
          script: skip
          deploy:
              - provider: pages
                skip_cleanup: true
                github_token: $GH_TOKEN
                local_dir: dist/examples
