name: CI-CD

# Trigger the workflow on pull request
on: [pull_request]

jobs:
    cache-npm-dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: node_modules

    lint-components:
        runs-on: ubuntu-latest
        name: Lint /components
        needs: [cache-npm-dependencies]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: node_modules
            - run: npm run lint components

    lint-doc-lib:
        runs-on: ubuntu-latest
        name: Lint /doc-lib
        needs: [cache-npm-dependencies]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: node_modules
            - run: npm run lint doc-lib

    lint-examples:
        runs-on: ubuntu-latest
        name: Lint /examples
        needs: [cache-npm-dependencies]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: node_modules
            - run: npm run lint examples

    build-components-lib:
        runs-on: ubuntu-latest
        name: Build /components
        needs: [lint-components]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: node_modules
            - uses: actions/cache@v1
              with:
                  path: ./dist/components
                  key: components
            - run: npm run build:components

    build-doc-lib:
        runs-on: ubuntu-latest
        name: Build /doc-lib
        needs: [lint-doc-lib]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: node_modules
            - uses: actions/cache@v1
              with:
                  path: ./dist/doc-lib
                  key: doc-lib
            - run: npm run build:doc-lib

    build-app:
        runs-on: ubuntu-latest
        name: Build /examples
        needs: [lint-examples, build-components-lib, build-doc-lib]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: node_modules
            - uses: actions/cache@v1
              with:
                  path: ./dist/doc-lib
                  key: doc-lib
            - uses: actions/cache@v1
              with:
                  path: ./dist/components
                  key: components
            - run: npm run build:examples
