name: CI-CD

# Trigger the workflow on pull request
on: [pull_request]

jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm install

    lint-components:
        runs-on: ubuntu-latest
        name: Lint /components
        needs: [prepare]
        steps:
            - uses: actions/checkout@v2
            - run: |
                  npm install
                  npm run lint components
    lint-doc-lib:
        runs-on: ubuntu-latest
        name: Lint /doc-lib
        needs: [prepare]
        steps:
            - uses: actions/checkout@v2
            - run: npm run lint doc-lib
    lint-examples:
        runs-on: ubuntu-latest
        name: Lint /examples
        needs: [prepare]
        steps:
            - uses: actions/checkout@v2
            - run: npm run lint examples

    build-components-lib:
        runs-on: ubuntu-latest
        name: Build /components
        needs: [lint-components, lint-doc-lib, lint-examples]
        steps:
            - uses: actions/checkout@v2
            - run: npm run build:components
    build-doc-lib:
        runs-on: ubuntu-latest
        name: Build /doc-lib
        needs: [lint-components, lint-doc-lib, lint-examples]
        steps:
            - uses: actions/checkout@v2
            - run: npm run build:doc-lib
    build-app:
        runs-on: ubuntu-latest
        name: Build /examples
        needs: [build-components-lib, build-doc-lib]
        steps:
            - uses: actions/checkout@v2
            - run: npm run build:examples
